name: pre-commit
description: Execute pre-commit for Terraform codebase
inputs:
  terraform-version:
    description: Terraform version supported for use in evaluation
    required: true
  terraform-docs-version:
    description: Version of terraform-docs to use when evaluating checks
    required: false
    default: v0.16.0
  terraform-tflint-version:
    description: Version of terraform-tflint to use when evaluating checks
    required: false
    default: v0.33.1
  terraform-tfsect-version:
    description: Version of terraform-tfsec to use when evaluating checks
    required: false
    default: v0.60.1
  args:
    description: Arguments to pass to pre-commit
    required: false
    default: '--all-files --color always --show-diff-on-failure'

runs:
  using: composite
  steps:
    - name: Install Terraform v${{ inputs.terraform-version }}
      shell: bash
      run: |
        curl -sO https://releases.hashicorp.com/terraform/${{ inputs.terraform-version }}/terraform_${{ inputs.terraform-version }}_linux_amd64.zip
        unzip -qq terraform_${{ inputs.terraform-version }}_linux_amd64.zip && rm terraform_${{ inputs.terraform-version }}_linux_amd64.zip 2> /dev/null && sudo mv terraform /usr/bin/

    - name: Install pre-commit dependencies
      shell: bash
      run: |
        pip install -q pre-commit
        curl -sLo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/${{ inputs.terraform-docs-version }}/terraform-docs-${{ inputs.terraform-docs-version }}-Linux-amd64.tar.gz && tar -xzf terraform-docs.tar.gz terraform-docs && chmod +x terraform-docs && sudo mv terraform-docs /usr/bin/
        curl -sLo ./terraform-tflint.zip https://github.com/terraform-linters/tflint/releases/download/${{ inputs.terraform-tflint-version }}/tflint_linux_amd64.zip && unzip -qq terraform-tflint.zip && chmod +x tflint && sudo mv tflint /usr/bin/
        curl -sLo ./tfsec https://github.com/tfsec/tfsec/releases/download/${{ inputs.terraform-tfsect-version }}/tfsec-linux-amd64 && chmod +x tfsec && sudo mv tfsec /usr/bin/

    - name: Execute tflint init
      shell: bash
      run: tflint --init

    - name: Execute pre-commit
      shell: bash
      run: pre-commit run ${{ inputs.args }}
